# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='PLATE',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
